### ISSUE TITLE
Warning message when building for production

### ISSUE THREAD

**Issue by arundhaj** [makimenko/angular-three-examples#3]
When building the application for production, I get the following warning.
How to get rid of this warning?

```
D:\angular-three-examples-master>ng build --prod
```

```
Date: 2018-01-30T09:27:38.945Z
Hash: 852fc05be81b829cb151
Time: 39138ms
chunk {0} polyfills.12c8097dc1606bc2ea5e.bundle.js (polyfills) 98.2 kB [initial] [rendered]
chunk {1} main.5bf78b443b4f685ee5f0.bundle.js (main) 727 kB [initial] [rendered]
chunk {2} styles.9c0ad738f18adc3d19ed.bundle.css (styles) 79 bytes [initial] [rendered]
chunk {3} inline.30555f13863256f8cb92.bundle.js (inline) 1.45 kB [entry] [rendered]

WARNING in ./src/app/scene/scene.component.ts
24:25-44 "export 'ColladaLoader' (imported as 'THREE') was not found in 'three'
    at HarmonyImportSpecifierDependency._getErrors (D:\angular-three-examples-master\node_modules\webpack\lib\dependenci
es\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\angular-three-examples-master\node_modules\webpack\lib\dependenc
ies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\angular-three-examples-master\node_modules\webpack\lib\Compilat
ion.js:703:24)
    at Compilation.finish (D:\angular-three-examples-master\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (D:\angular-three-examples-master\node_modules\webpack\lib\Compiler.js:502:17)
    at D:\angular-three-examples-master\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\angular-three-examples-master\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (D:\angular-three-examples-master\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./src/app/scene/scene.component.ts
 @ ./src/app/app.component.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./src/app/scene/scene.component.ts
76:28-47 "export 'OrbitControls' (imported as 'THREE') was not found in 'three'
    at HarmonyImportSpecifierDependency._getErrors (D:\angular-three-examples-master\node_modules\webpack\lib\dependenci
es\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\angular-three-examples-master\node_modules\webpack\lib\dependenc
ies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\angular-three-examples-master\node_modules\webpack\lib\Compilat
ion.js:703:24)
    at Compilation.finish (D:\angular-three-examples-master\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (D:\angular-three-examples-master\node_modules\webpack\lib\Compiler.js:502:17)
    at D:\angular-three-examples-master\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\angular-three-examples-master\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (D:\angular-three-examples-master\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./src/app/scene/scene.component.ts
 @ ./src/app/app.component.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**Comment by makimenko** [comment]
Dear Arunkumar,

Warning message will be visible until “threejs/examples/js” not transformed to support modules (see threejs [#9562](https://github.com/mrdoob/three.js/issues/9562)).
For now, just ignore warning message (ng build --prod should create all necessary and fully working code for you in dist folder).

Best Regards,
Mihail
